from pydantic import BaseModel, Field
from typing import List, Optional


class RawPredictionItem(BaseModel):
    label: str = Field(..., description="Class label returned by the Hugging Face model")
    score: float = Field(..., description="Confidence score between 0.0 and 1.0")


class ClinicalSummary(BaseModel):
    primary_finding: str = Field(..., description="Key diagnostic finding")
    confidence_assessment: str = Field(..., description="Explanation of model confidence")
    key_observations: List[str] = Field(default_factory=list, description="Clinical points")
    recommended_next_steps: List[str] = Field(default_factory=list, description="Actionable recommendations")
    disclaimer: str = Field(
        default="This output is generated by an AI decision-support system and does not constitute a formal medical diagnosis. All findings must be validated by a licensed physician.",
        description="Medical safety disclaimer"
    )


class DiagnosticResponse(BaseModel):
    status: str = Field(default="success")
    disease_id: str
    disease_name: str
    modality: str
    top_prediction: RawPredictionItem
    raw_predictions: List[RawPredictionItem]
    clinical_summary: Optional[ClinicalSummary] = None